//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cinema_Web_Entities : DbContext
    {
        public Cinema_Web_Entities()
            : base("name=Cinema_Web_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actors { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<director> directors { get; set; }
        public virtual DbSet<discount> discounts { get; set; }
        public virtual DbSet<display_date> display_date { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<movie_actor> movie_actor { get; set; }
        public virtual DbSet<movie_display_date> movie_display_date { get; set; }
        public virtual DbSet<movie_review> movie_review { get; set; }
        public virtual DbSet<movie_type> movie_type { get; set; }
        public virtual DbSet<movy> movies { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<room_schedule_detail> room_schedule_detail { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<schedule_detail> schedule_detail { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<seat_status> seat_status { get; set; }
        public virtual DbSet<star_rating> star_rating { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<user_discount> user_discount { get; set; }
        public virtual DbSet<user_profile> user_profile { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
        public virtual DbSet<user_type_user_role> user_type_user_role { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
    }
}
