//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_detail
    {
        public int id { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public Nullable<int> display_date_id { get; set; }
    
        public virtual display_date display_date { get; set; }
        public virtual schedule schedule { get; set; }
    }
}
