//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat_status
    {
        public int id { get; set; }
        public Nullable<int> seat_id { get; set; }
        public Nullable<int> room_schedule_detail_id { get; set; }
        public Nullable<bool> is_booked { get; set; }
    
        public virtual room_schedule_detail room_schedule_detail { get; set; }
        public virtual seat seat { get; set; }
    }
}
