//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class star_rating
    {
        public int id { get; set; }
        public Nullable<decimal> rating_value { get; set; }
        public Nullable<int> movie_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual movy movy { get; set; }
        public virtual user user { get; set; }
    }
}
