//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> is_host { get; set; }
        public Nullable<int> total_spend { get; set; }
        public string url_avatar { get; set; }
    
        public virtual user user { get; set; }
    }
}
