//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_discount
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> discount_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> discount_status { get; set; }
    
        public virtual discount discount { get; set; }
        public virtual user user { get; set; }
    }
}
